[build]
    publish = ".next"
    command = "next build"
    node_bundler = "esbuild"

[dev]
    publish = "public"
    node_bundler = "esbuild"
    port = 8888

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200
